<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?php echo $this->layout['title'];?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="kovey">
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/static/css/layout.css">
    </head>

    <body>
        <div style="min-height:100%;">
            <main role="main" class="container-fluid" style="height:100%;">
                <div class="ko-global-div-center">
                    <?php echo $this->content;?>
                </div>
            </main>
            <div id="ko-global-spinner" class="ko-global-div-center" style="z-index:9999;display:none;">
            </div>
            <div aria-live="polite" aria-atomic="true" class="ko-global-div-center" style="display:none;" id="ko-global-prompt-div">
              <div id="ko-global-prompt" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="1000" style="z-index:9999;">
                <div class="toast-header">
                  <strong class="mr-auto">提示！</strong>
                  <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="toast-body" id="ko-prompt-body">
                </div>
              </div>
            </div>
        </div>
        <footer class="ko-footer text-muted" style="text-align:center;"> 
            <p>    
            Powered by: <a href="http://www.kovey.cn/">Kovey</a> Copyright © 2018-<?php echo date('Y');?> Kovey.
          </p>
        </footer>
        <script type="text/javascript" src="/static/js/jquery.min.js"></script>
        <script type="text/javascript" src="/static/js/popper.min.js"></script>
        <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    </body
</html>
